# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
run_irlba <- function(x, init, number, work) {
    .Call('_irlba_tests_run_irlba', PACKAGE = 'irlba.tests', x, init, number, work)
}

