# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dense <- function(x, init, number, work, tol, num_threads) {
    .Call('_irlba_tests_dense', PACKAGE = 'irlba.tests', x, init, number, work, tol, num_threads)
}

parallel <- function(nrow, ncol, x, i, p, init, number, work, tol, num_threads) {
    .Call('_irlba_tests_parallel', PACKAGE = 'irlba.tests', nrow, ncol, x, i, p, init, number, work, tol, num_threads)
}

sparse <- function(nrow, ncol, x, i, p, init, number, work, tol, num_threads) {
    .Call('_irlba_tests_sparse', PACKAGE = 'irlba.tests', nrow, ncol, x, i, p, init, number, work, tol, num_threads)
}

